package com.example.deninternship_week5.Quiz.jetUi
// Question data model
data class Question(
    val questionText: String,
    val options: List<String>,
    val correctAnswerIndex: Int
)
object QuestionData {
    val computerNetworksQuestions = listOf(
        Question("What is the purpose of the OSI model?",
            listOf("To encrypt data", "To describe network protocols", "To speed up internet", "To manage hardware"), 1),
        Question("How many layers are in the OSI model?",
            listOf("5", "6", "7", "8"), 2),
        Question("Which layer in the OSI model is responsible for routing?",
            listOf("Transport", "Network", "Data Link", "Application"), 1),
        Question("TCP stands for?",
            listOf("Transfer Control Protocol", "Transmission Control Protocol", "Time Control Protocol", "Traffic Control Protocol"), 1),
        Question("What does IP stand for?",
            listOf("Internet Protocol", "Internal Process", "International Packet", "Input Protocol"), 0),
        Question("Which protocol uses a three-way handshake?",
            listOf("UDP", "FTP", "TCP", "HTTP"), 2),
        Question("Which layer handles MAC addressing?",
            listOf("Application", "Data Link", "Network", "Transport"), 1),
        Question("What is the maximum length of an IPv4 address in bits?",
            listOf("32", "64", "128", "16"), 0),
        Question("Which layer encrypts data?",
            listOf("Presentation", "Session", "Network", "Transport"), 0),
        Question("Which of these is a transport layer protocol?",
            listOf("HTTP", "TCP", "IP", "FTP"), 1),
        Question("What is the function of ARP?",
            listOf("Route packets", "Translate IP to MAC", "Encrypt data", "Send mail"), 1),
        Question("Which device operates at Layer 3?",
            listOf("Hub", "Switch", "Router", "Bridge"), 2),
        Question("Which layer ensures reliable transmission?",
            listOf("Data Link", "Transport", "Application", "Session"), 1),
        Question("What is the default port for HTTP?",
            listOf("21", "22", "80", "443"), 2),
        Question("What is the purpose of a firewall?",
            listOf("Enhance speed", "Connect networks", "Provide security", "Store data"), 2),
        Question("Which protocol sends emails?",
            listOf("SMTP", "FTP", "SNMP", "HTTP"), 0),
        Question("Which protocol retrieves emails?",
            listOf("POP3", "SMTP", "HTTP", "DNS"), 0),
        Question("What is DNS used for?",
            listOf("Download data", "Map domain names to IPs", "Send messages", "Secure traffic"), 1),
        Question("Which layer creates sessions?",
            listOf("Application", "Transport", "Session", "Network"), 2),
        Question("Which protocol does not guarantee delivery?",
            listOf("TCP", "UDP", "FTP", "SMTP"), 1),
        // 30 more CN questions below
        Question("What is the full form of FTP?", listOf("File Transfer Protocol", "File Transit Process", "Fast Transfer Protocol", "Free Transfer Port"), 0),
        Question("Which port is used by DNS?", listOf("53", "80", "25", "110"), 0),
        Question("What is an IP address?", listOf("A physical address", "A device name", "A unique identifier for a device on a network", "A type of protocol"), 2),
        Question("Which protocol is used for secure web browsing?", listOf("HTTP", "HTTPS", "FTP", "TCP"), 1),
        Question("Which layer is responsible for end-to-end delivery?", listOf("Transport", "Network", "Session", "Data Link"), 0),
        Question("Which device broadcasts packets to all devices?", listOf("Router", "Switch", "Bridge", "Hub"), 3),
        Question("Which protocol helps in assigning IP addresses?", listOf("DHCP", "DNS", "FTP", "HTTP"), 0),
        Question("What is a MAC address?", listOf("Network address", "Software ID", "Hardware address", "Routing protocol"), 2),
        Question("Which address is used to identify a device globally?", listOf("IP address", "MAC address", "Subnet", "Host ID"), 0),
        Question("What is subnetting?", listOf("Dividing IP network", "Joining networks", "Blocking traffic", "Encrypting data"), 0),
        Question("How many bits are in an IPv6 address?", listOf("64", "128", "32", "256"), 1),
        Question("Which layer breaks data into segments?", listOf("Transport", "Network", "Data Link", "Application"), 0),
        Question("Which one is connectionless?", listOf("TCP", "HTTP", "UDP", "FTP"), 2),
        Question("Which protocol is used in Ping command?", listOf("ICMP", "TCP", "UDP", "HTTP"), 0),
        Question("Which device separates two networks?", listOf("Router", "Switch", "Hub", "Bridge"), 0),
        Question("Which is not a network topology?", listOf("Star", "Ring", "Bus", "Point"), 3),
        Question("Which protocol is used to access web pages?", listOf("HTTP", "SMTP", "FTP", "ARP"), 0),
        Question("What is the maximum length of a MAC address?", listOf("48 bits", "32 bits", "16 bits", "64 bits"), 0),
        Question("Which device uses IP address to forward data?", listOf("Router", "Hub", "Switch", "Modem"), 0),
        Question("Which protocol is used to transfer files?", listOf("FTP", "HTTP", "SMTP", "SNMP"), 0),
        Question("What is the primary purpose of NAT?", listOf("Network security", "IP address translation", "Speed enhancement", "Data encryption"), 1),
        Question("Which port is used by HTTPS?", listOf("443", "80", "21", "23"), 0),
        Question("Which OSI layer is closest to the user?", listOf("Application", "Session", "Transport", "Data Link"), 0),
        Question("Which protocol is used for remote login?", listOf("Telnet", "HTTP", "FTP", "SMTP"), 0),
        Question("What is a packet?", listOf("A file", "A network address", "A unit of data", "A protocol"), 2),
        Question("What layer is HTTP in?", listOf("Application", "Transport", "Network", "Session"), 0),
        Question("What is a port number?", listOf("A network address", "An identifier for services", "A MAC address", "A subnet"), 1),
        Question("What is latency?", listOf("Data size", "Network delay", "Speed", "IP translation"), 1),
        Question("Which protocol is faster but less reliable?", listOf("TCP", "UDP", "HTTP", "SMTP"), 1),
        Question("Which of these uses TCP?", listOf("VoIP", "Streaming", "Web browsing", "Live gaming"), 2)
    )

    val androidDevelopmentQuestions = listOf(
        Question("What is the main language used in Android development?", listOf("Kotlin", "Swift", "C#", "JavaScript"), 0),
        Question("What does APK stand for?", listOf("Android Phone Kit", "Android Package", "App Program Kernel", "Android Power Kit"), 1),
        Question("What is the base class for layouts in Android?", listOf("View", "ViewGroup", "Activity", "Intent"), 1),
        Question("Which file contains app permissions?", listOf("MainActivity.kt", "styles.xml", "AndroidManifest.xml", "build.gradle"), 2),
        Question("What is the entry point for an Android app?", listOf("Application", "MainActivity", "onCreate()", "Intent"), 1),
        Question("Which component is not part of Android architecture?", listOf("Activity", "Fragment", "Service", "Middleware"), 3),
        Question("Which layout stacks children vertically?", listOf("LinearLayout", "RelativeLayout", "FrameLayout", "ConstraintLayout"), 0),
        Question("What is the function of an Intent?", listOf("Draw UI", "Store data", "Start activities/services", "Play sound"), 2),
        Question("Which method is called when an Activity is created?", listOf("onStart()", "onResume()", "onCreate()", "onPause()"), 2),
        Question("Which folder contains drawable resources?", listOf("res/layout", "res/values", "res/drawable", "res/mipmap"), 2),
        Question("Which tool compiles XML to binary?", listOf("Gradle", "AAPT", "JVM", "Dex"), 1),
        Question("What is RecyclerView used for?", listOf("Animations", "Lists", "Navigation", "Media playback"), 1),
        Question("Jetpack Compose is used for?", listOf("Networking", "UI Design", "Database", "Security"), 1),
        Question("Which Jetpack library manages data in UI?", listOf("LiveData", "ViewModel", "Room", "NavController"), 1),
        Question("Which lifecycle method is called before activity becomes visible?", listOf("onPause()", "onResume()", "onStart()", "onCreate()"), 2),
        Question("What does Gradle do in Android?", listOf("Manage app UI", "Draw XML", "Build and dependency management", "Send notifications"), 2),
        Question("What is ANR?", listOf("Android Network Routing", "Application Not Responding", "Async Network Request", "Activity Notification Reset"), 1),
        Question("Which annotation is used for Room Entity?", listOf("@Database", "@Dao", "@Entity", "@Model"), 2),
        Question("Room is part of?", listOf("Firebase", "Jetpack", "Material Design", "Kotlin DSL"), 1),
        Question("What does Toast in Android do?", listOf("Log errors", "Show popup message", "Crash app", "Play music"), 1),
        Question("What’s used for navigation in Compose?", listOf("Intent", "NavController", "ActivityManager", "Router"), 1),
        Question("Which ViewGroup is most flexible?", listOf("FrameLayout", "ConstraintLayout", "LinearLayout", "RelativeLayout"), 1),
        Question("Which is used for background work?", listOf("BroadcastReceiver", "AsyncTask", "WorkManager", "ServiceManager"), 2),
        Question("Which file defines app theme?", listOf("theme.xml", "colors.xml", "strings.xml", "styles.xml"), 3),
        Question("What is the purpose of ViewModel?", listOf("Manage layouts", "Control app permissions", "Store and manage UI-related data", "Show data in RecyclerView"), 2),
        Question("Which library is used for image loading?", listOf("OkHttp", "Glide", "Room", "Retrofit"), 1),
        Question("Which is NOT a UI component?", listOf("Text", "Column", "ViewModel", "Button"), 2),
        Question("Which is NOT a Jetpack component?", listOf("LiveData", "Room", "Retrofit", "Navigation"), 2),
        Question("Which function launches a coroutine in Compose?", listOf("launchEffect", "rememberCoroutine", "LaunchedEffect", "delayEffect"), 2),
        Question("What does MutableState hold?", listOf("Immutable values", "Changing UI state", "Database info", "Static strings"), 1),
        Question("Which method is used to finish activity?", listOf("end()", "stop()", "destroy()", "finish()"), 3),
        Question("How to start another activity?", listOf("startActivity(intent)", "launchActivity()", "open()", "navigate()"), 0),
        Question("How to observe LiveData?", listOf("watch()", "observe()", "listen()", "trigger()"), 1),
        Question("Which keyword creates a Composable function?", listOf("fun", "comp", "Compos", "@Composable"), 3),
        Question("In Compose, how to remember value across recomposition?", listOf("remember", "state", "mutable", "observe"), 0),
        Question("What is Scaffold used for?", listOf("UI layout structure", "Database schema", "Navigation", "Animations"), 0),
        Question("Which is NOT a lifecycle method?", listOf("onStop()", "onDestroy()", "onSleep()", "onPause()"), 2),
        Question("What is MaterialTheme used for?", listOf("State handling", "Custom fonts", "Styling UI", "App logic"), 2),
        Question("What is used for async networking?", listOf("Glide", "Coroutine", "Room", "Intent"), 1),
        Question("What is context in Android?", listOf("App state", "UI state", "Permissions", "App environment info"), 3),
        Question("What is Retrofit?", listOf("Database", "Image Loader", "HTTP client", "UI layout"), 2),
        Question("Which one saves key-value pairs?", listOf("Room", "SQLite", "SharedPreferences", "Firebase"), 2),
        Question("What is Splash Screen?", listOf("Error screen", "First screen of app", "Login screen", "Exit screen"), 1),
        Question("What is dp in Android?", listOf("Digital pixel", "Device pixel", "Density-independent pixel", "Dot pitch"), 2),
        Question("Which class holds UI for Compose?", listOf("ComposeView", "Composable", "Activity", "Fragment"), 1),
        Question("What does .collect{} do?", listOf("Observe flow", "Launch coroutine", "Stop UI", "Create View"), 0),
        Question("Which package is NOT Android native?", listOf("androidx.compose.*", "android.os.*", "android.widget.*", "com.apple.ios"), 3),
        Question("Which tool creates APK?", listOf("Gradle", "JVM", "Logcat", "Android Profiler"), 0)
    )

    val dsaQuestions = listOf(
        Question("What is the time complexity of binary search?", listOf("O(n)", "O(log n)", "O(n log n)", "O(1)"), 1),
        Question("Which data structure uses FIFO order?", listOf("Stack", "Queue", "Tree", "Graph"), 1),
        Question("Which sorting algorithm is best for nearly sorted data?", listOf("Bubble Sort", "Selection Sort", "Insertion Sort", "Quick Sort"), 2),
        Question("What is the space complexity of merge sort?", listOf("O(n)", "O(1)", "O(log n)", "O(n log n)"), 0),
        Question("What data structure is used for DFS traversal?", listOf("Queue", "Stack", "Heap", "Tree"), 1),
        Question("Which algorithm is used to find shortest path in weighted graphs?", listOf("DFS", "BFS", "Dijkstra", "Kruskal"), 2),
        Question("Which of the following is not a linear data structure?", listOf("Array", "Stack", "Queue", "Tree"), 3),
        Question("Which traversal is used for BST to get sorted output?", listOf("Preorder", "Inorder", "Postorder", "Level Order"), 1),
        Question("What is a hash function?", listOf("Encrypts data", "Converts input to index", "Sorts data", "Compares strings"), 1),
        Question("Which data structure gives O(1) average search time?", listOf("Array", "Linked List", "Hash Table", "BST"), 2),
        Question("Which algorithm is used in minimum spanning tree?", listOf("Prim’s", "DFS", "KMP", "Bellman-Ford"), 0),
        Question("Which data structure uses LIFO?", listOf("Queue", "Array", "Stack", "Tree"), 2),
        Question("In heap, which node has the highest priority in max heap?", listOf("Leaf", "Middle", "Root", "Right child"), 2),
        Question("How many pointers does a node in doubly linked list have?", listOf("1", "2", "3", "4"), 1),
        Question("Which sorting is in-place?", listOf("Merge Sort", "Heap Sort", "Counting Sort", "Bucket Sort"), 1),
        Question("Which algorithm uses divide and conquer?", listOf("Binary Search", "Bubble Sort", "BFS", "DFS"), 0),
        Question("Which is not a comparison-based sorting?", listOf("Quick Sort", "Merge Sort", "Radix Sort", "Heap Sort"), 2),
        Question("Which tree is balanced and ordered?", listOf("BST", "Heap", "B-Tree", "Trie"), 2),
        Question("Which traversal is BFS?", listOf("Depth first", "Breadth first", "Random", "Topological"), 1),
        Question("Which data structure is used in recursion?", listOf("Queue", "Stack", "Tree", "Graph"), 1),
        Question("What is the height of an empty tree?", listOf("-1", "0", "1", "Null"), 0),
        Question("Which tree allows duplicates?", listOf("Binary Search Tree", "Heap", "Trie", "None"), 0),
        Question("Which sorting algorithm is best in worst case?", listOf("Merge Sort", "Quick Sort", "Bubble Sort", "Heap Sort"), 0),
        Question("Which data structure is used in BFS?", listOf("Stack", "Queue", "Array", "Tree"), 1),
        Question("What is the time complexity of inserting at end of array?", listOf("O(1)", "O(n)", "O(log n)", "O(n log n)"), 0),
        Question("Which is best for priority queue?", listOf("Stack", "Array", "Heap", "Tree"), 2),
        Question("Which structure is used for undo operations?", listOf("Queue", "Array", "Stack", "Heap"), 2),
        Question("What is the max edges in undirected graph with n vertices?", listOf("n(n+1)/2", "n(n-1)/2", "n^2", "2n"), 1),
        Question("Which graph algorithm detects cycle?", listOf("BFS", "DFS", "Topological Sort", "Both B and C"), 3),
        Question("Which algorithm is used for pattern matching?", listOf("KMP", "Bellman-Ford", "Floyd Warshall", "Prim"), 0),
        Question("Which traversal visits root first?", listOf("Inorder", "Preorder", "Postorder", "None"), 1),
        Question("What is the in-degree of isolated node?", listOf("0", "1", "2", "Depends"), 0),
        Question("Which algorithm is used in shortest path with negative weights?", listOf("Dijkstra", "Bellman-Ford", "Prim", "Kruskal"), 1),
        Question("Which traversal visits all children before next level?", listOf("Inorder", "Postorder", "BFS", "DFS"), 2),
        Question("Which is not a self-balancing tree?", listOf("AVL", "Red-Black", "B-Tree", "Binary Heap"), 3),
        Question("Which of the following is non-linear?", listOf("Array", "Linked List", "Stack", "Graph"), 3),
        Question("Which operation takes O(1) in stack?", listOf("Search", "Pop", "Traversal", "Sort"), 1),
        Question("Which uses O(n^2) in worst case?", listOf("Merge Sort", "Heap Sort", "Quick Sort", "Bubble Sort"), 3),
        Question("Which of the following is a greedy algorithm?", listOf("Kruskal", "Bellman-Ford", "Floyd-Warshall", "Dijkstra"), 0),
        Question("Which data structure implements map?", listOf("Array", "Hash Table", "Stack", "Queue"), 1),
        Question("How many children can binary tree node have?", listOf("1", "2", "3", "Any"), 1),
        Question("Which data structure supports fast prefix search?", listOf("Array", "Heap", "Trie", "Tree"), 2),
        Question("Which sorting algorithm is not stable?", listOf("Bubble Sort", "Merge Sort", "Heap Sort", "Insertion Sort"), 2),
        Question("Which algorithm is used in topological sort?", listOf("DFS", "BFS", "Dijkstra", "Kruskal"), 0),
        Question("What’s the best case of linear search?", listOf("O(n)", "O(log n)", "O(1)", "O(n^2)"), 2),
        Question("What does adjacency matrix store?", listOf("Vertex list", "Edge list", "Edge weights", "All edges in matrix"), 3),
        Question("What’s a sparse matrix?", listOf("Filled matrix", "Matrix with all 1s", "Mostly 0s", "Small matrix"), 2),
        Question("Which queue allows insertion and deletion at both ends?", listOf("Simple Queue", "Priority Queue", "Deque", "Circular Queue"), 2),
        Question("Which algorithm is not divide and conquer?", listOf("Merge Sort", "Quick Sort", "Binary Search", "Bubble Sort"), 3),
        Question("Which of these is NOT a tree?", listOf("B-Tree", "Red-Black Tree", "Binary Heap", "Hash Table"), 3),
        Question("Which method removes from the front in queue?", listOf("Push", "Enqueue", "Dequeue", "Peek"), 2)
    )
}

